
image: openjdk:11.0.13-jre-slim

build-job:test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

RunUITests:
  stage: test
  script:
    - pwd