
image: openjdk:11

build-job:test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - java -version