runTests:
  variables:
    UPSTREAM_CI_JOB_TOKEN: $CI_JOB_TOKEN
  trigger:
    include: .gitlab-ci-tests-run.yml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

buildProject:
  script: echo "Build Project"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always