
image: openjdk:11.0

stages:
  - Test
  - Report
  - Deploy

.download_history: &download_history
  after_script:
    - mkdir backup && cd backup || true
    - "curl --location --output report.zip --request GET \"https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/main/download?job=pages\" --header \"Authorization: Bearer ${CI_DEPLOY_TOKEN}\" || true"
    - (unzip report.zip) || true
    - cd ../
    - ls
    - (cp -r backup/public/history/ allure-results/history) || true

.Test: &Test
  allow_failure: true
  stage: Test
  script:
    -  echo "$CI_PROJECT_ID" and "$CI_DEPLOY_TOKEN."
    - ./gradlew web-ui-tests-junit5:build
  artifacts:
    when: always
    paths:
      - web-ui-tests-junit5/build/reports/allure-report
    expire_in: 1 week

smoke::
  <<: *Test
  <<: *download_history

Report:
  stage: Report
  script:
    - ./gradlew web-ui-tests-junit5:allureReport
    - ls web-ui-tests-junit5/build/allure-results
    - ls web-ui-tests-junit5/build/reports/allure-report
  artifacts:
    when: always
    paths:
      - web-ui-tests-junit5/build/allure-results
      - web-ui-tests-junit5/build/reports/allure-report
    expire_in: 1 week

pages:
  stage: Deploy
  when: always
  dependencies:
    - Report
  script:
    - mv web-ui-tests-junit5/build/reports/allure-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
