stages:
  - Build
  - Test
  - Report
  - Deploy

.runTestsRule:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

RunTests:
  stage: Test
  allow_failure: true
  script:
    - echo "Run Tests"
  extends: .runTestsRule

DownloadAllureHistory:
  stage: Test
  dependencies:
    - RunTests
  script:
    - echo "Test download_history"
  extends: .runTestsRule

Report:
  stage: Report
  dependencies:
    - RunTests
  script:
    - echo "Report"
  extends: .runTestsRule

Pages:
  stage: Deploy
  dependencies:
    - Report
  script:
    - echo "pages"
  extends: .runTestsRule

buildProject:
  stage: Build
  script: echo "Build Project"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always

