
image: openjdk:11.0

stages:
  - Test
  - Report

Test:
  stage: Test
  script:
    - ./gradlew web-ui-tests-junit5:build
    - ./gradle web-ui-tests-junit5:allureReport
  artifacts:
    when: always
    paths:
      - web-ui-tests-junit5/build/allure-results
    expire_in: 1 week


Report:
  stage: Report
  script:
    - mkdir public
    - mv web-ui-tests-junit5/build/allure-results/* public
  artifacts:
    when: always
    paths:
      - public
    expire_in: 1 week


