
image: openjdk:11.0.13-jre-slim

stages:
  - build
  - test
  - report

Build:
  stage: build
  script: 
    - ./gradlew clean build --stacktrace

RunUITests:
  stage: test
  script:
    - pwd










build-job:test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"