runTests:
  variables:
    UPSTREAM_CI_JOB_TOKEN: $PETRO_PERSONAL_TOKEN
  trigger:
    include: .gitlab-ci-tests-run.yml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "scheduled"'
      when: always


buildProject:
  script: echo "Build Project"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
