
image: gradle:alpine

# stages:
#   - test

RunUITests:
  stage: test
  script:
    - ./gradlew web-ui-tests-junit5:build








build-job:test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"