version: '3'
services:
  chromeDriver:
    image: selenoid/vnc:chrome_91.0
  videoRecorder:
    image: selenoid/video-recorder:latest-release
  selenoid:
    image: aerokube/selenoid:latest-release
    networks:
      - selenoid
    volumes:
      - "${PWD}/./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/./config/video:/opt/selenoid/video"
      - "${PWD}/./config/logs:/opt/selenoid/logs"
    command: [ "-conf", "/etc/selenoid/browsers.json",
               "-video-output-dir", "/opt/selenoid/video",
               "-log-output-dir", "/opt/selenoid/logs",
               "-container-network", "selenoid",
               "-timeout", "10m",
               "-enable-file-upload", ]
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/./config/video
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    networks:
      - selenoid
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
networks:
  selenoid:
      name: selenoid
