version: "3"
services:
  selenium-hub:
    image: seleniarm/hub:4.8.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: seleniarm/node-chromium:109.0
    volumes:
      - /dev/shm:/dev/shm
    shm_size: "2gb"
    ports:
      - "6900:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - selenium-hub